### ISSUE TITLE
[1.12.2]Items are not consumed

### ISSUE THREAD

**Issue by Ironnoob73** [TinyModularThings/Scavenge#21]
The "consume_player_items" does not consume player items. Log errors are:
```
[13:35:14] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_372]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_372]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911) ~[?:1.8.0_372]
	at java.util.ArrayList$Itr.next(ArrayList.java:861) ~[?:1.8.0_372]
	at scavenge.player.blockEffects.PropPlayerConumeItems.applyEffects(PropPlayerConumeItems.java:68) ~[PropPlayerConumeItems.class:?]
	at scavenge.core.builder.block.BlockResource.applyEffect(BlockResource.java:199) ~[BlockResource.class:?]
	at scavenge.core.handlers.ScavengeHandler.onBlockRightClick(ScavengeHandler.java:81) ~[ScavengeHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_146_ScavengeHandler_onBlockRightClick_RightClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137) ~[ForgeHooks.class:14.23.5.2860]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:433) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_372]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_372]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 5 more
```
The contents of the file I wrote:
```
{
    "block_pools": [
        {
            "name": "Frame0",
            "type": {
                "type": "block",
                "name": "minecraft:planks"
            },
            "clicktype": "right",
            "properties": [
                {
                    "type":"require_item",
                    "name":"minecraft:stone_pickaxe"
                },
                {
                    "type":"player_has_items",
                    "items":[
                        {"name":"minecraft:stick"},
                        {"name":"minecraft:paper"}
                    ]
                },
                {
                    "type":"consume_block",
                    "name":"minecraft:jukebox"
                },
                {
                    "type":"require_sneak"
                },
                {
                    "type":"consume_player_items",
                    "items":{"name":"minecraft:stick"}
                }
            ],
            "drops": [
            ],
            "messages": [
                {
                    "id":"require_sneak",
                    "message":"⍔"
                },
                {
                    "id":"player_has_items",
                    "message":"⌸"
                }
            ]
        }
    ]
}
```

**Comment by Speiger** [comment]
Sorry but i don't have the 1.12. sourcecode anymore.
So its no longer supported.
